name: Cypress Tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificar diretório de screenshots
        run: mkdir -p cypress/screenshots

      - name: Executar testes (Cypress - modo headless)
        run: |
          export TERM=xterm
          npx cypress run

      - name: Listar arquivos de screenshots
        run: ls -R cypress/screenshots

      - name: Upload de Screenshots (falhas ou screenshots manuais)
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-cypress
          path: cypress/screenshots
