name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes do Cypress (npm test)
        run: npm test

      - name: Salvar screenshots como artefato
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-cypress
          path: cypress/screenshots
